uses: Platane/snk@v3
  with:
    github_user_name: ${{JanaAlhumaidan}}
    outputs: |
      # Light mode contribution graph
      dist/github-snake.svg

      # Dark mode contribution graph
      dist/github-snake-dark.svg?palette=github-dark

      # Custom dark mode contribution graph with a different filename
      dist/github-snake-darkmode.svg?palette=github-dark
